yRCA bug fix
di-unipi-socc/yRCA pull request #4
Opened 2023-01-13 15:52 UTC by LucaRUnipi

I proposed a new rule for yRCA to successfully identify the case when an instance of service SI doesn't wait enough time for an instance of SJ reply. This specific case has not taken in consideration and yRCA returns a "Found no failure..." which is not the correct explanation.

2023-01-16 09:09 UTC, jsoldani commented
@teto1992 could you please check the PR, which - looks good to me and - should fix issue #3

2023-01-17 09:51 UTC, teto1992 requested changes
@LucaRUnipi the case is fine. Please add ASCII sketch in the comment.

2023-01-30 15:58 UTC, LucaRUnipi reviewed
Added ASCII sketch for new yRCA rule.

2023-01-31 07:40 UTC, teto1992 approved these changes

2023-01-31 07:40 UTC, merged